### ISSUE TITLE
Memcached key size can exceed 250 byte limit 

### ISSUE THREAD

**Issue by mbell697** [pkittenis/graphite-influxdb#11]
Memcached only allows keys up to 250 bytes in size, the current key gen scheme doesn't defend against exceeding this limit: https://github.com/pkittenis/graphite-influxdb/blob/master/graphite_influxdb/utils.py#L130

Usually using a hash of the original key is the best approach here (murmur, md5, etc).

**Comment by pkittenis** [comment]
Thanks for raising!
