### ISSUE TITLE
Which version of InfluxDB are supported

### ISSUE THREAD

**Issue by aborysov** [pkittenis/graphite-influxdb#16]
Which version of InfluxDB are supported and if it is plans to support with future releases of InfluxDB? We very happy about this project. It works with  InfluxDB 0.9.2, and it seems that dosn't work with influxdb_0.12.0-1_amd64.deb.
Thank you

**Comment by aborysov** [comment]
It is possible - now see it works with last influx

**Comment by pkittenis** [comment]
See [release notes for 0.5.3-rc1](https://github.com/pkittenis/graphite-influxdb/releases/tag/0.5.3rc1)
