### ISSUE TITLE
not working cache in memcached

### ISSUE THREAD

**Issue by balookrd** [pkittenis/graphite-influxdb#17]
data stored in memcached, but return randomed...

**Comment by pkittenis** [comment]
What issue is being reported? Can you please provide queries that replicate the issue.

**Comment by balookrd** [comment]
I configured use of memcached. According to the statistics I see memcached that there are only get-requests, and there is no set.

**Comment by pkittenis** [comment]
Impossible to know what is happening without a reproducible test. 

There will be nothing written to memcache if there is no influxdb data to write to it, for example and there will still be lots of missed get requests.

Can you please provide some sample requests showing data in the DB not being cached.

**Comment by balookrd** [comment]
how i can enable debug logging? i add "log_file" to config, but file is emty...

influxdb:
    db: graphite
    host: localhost
    port: 8086
    log_file: /u01/graphite-api/graphite-api.log

**Comment by balookrd** [comment]
I turned on the memcached, but I can not use it in the product. Render all charts in grafana stopped uwsgi process consume 100% cpu. But I close the ticket, because I do not have time to understand what's going on in the code. I'm using nginx caching to graphite-api. Thank you.

**Comment by pkittenis** [comment]
Nothing from what has been described so far makes this sound like an issue with graphite-influxdb.  More likely it is a configuration issue with something else, be it graphite-api, influxdb, memcached, or uwsgi.

If it can be shown how to reproduce it would be possible to confirm either way.

AFAIK memcache integration is working as expected and tests for it are passing.
