### ISSUE TITLE
misparse series names first node gets extra attributes

### ISSUE THREAD

**Issue by r3cgm** [pkittenis/graphite-influxdb#19]
Some times when graphite-influxdb fires off to get the full series listing and goes to populate the first node in a grafana dashboard graph, we get the expected dozen or so results:

applications
hosts
...
memory
servers

However, maybe half the time the parsing introduces extra results that look like this:

servers,host=web101
servers,host=web102
servers,host=web103

There shouldn't be anything after the "servers" here, but it seems to add a tag after the comma, or something... I'm not sure.

I thought originally this was only happening while series pagination was in effect but I changed the limit from 100000 to 200000 which can accommodate our metrics in a single page and the issue still happened sometimes.

Wish I knew what was causing this.

**Comment by pkittenis** [comment]
Probably an effect of having data with tags, which are not supported by graphite-influxdb, in the same DB as graphite metric data without tags. See [readme for information on lack of tag support](https://github.com/pkittenis/graphite-influxdb#influxdb-graphite-metric-templates).

If this is not the case can you please provide a test case that reproduces this issue with untagged graphite metric data.

**Comment by pkittenis** [comment]
To clarify the above, need for example come curl commands to add some of the data in your DB that is causing this so the error can be reproduced. 

While tagged metric data is not supported, they should not break series lists so will need to first reproduce in order to handle such data correctly.

**Comment by pkittenis** [comment]
Closing - tags unsupported per documentation and no reproducible steps have been provided. Can be re-opened if it can be shown how to reproduce.
