### ISSUE TITLE
Failed install with Python3.4

### ISSUE THREAD

**Issue by midse** [pkittenis/graphite-influxdb#2]
Hello pkittenis,

Thanks for this great fork. I had a few issues regarding the 0.5.0-rc2 release using Python3.4.

I have an "SyntaxError: invalid syntax" on line 104 using "python setup.py install" 
print get_git_version() --> print(get_git_version()) works better for me.

The RELEASE-VERSION file is not included so version.py can't find the version number. 

I don't know if you were aware of those issues.

Regards,
Dimitri

**Comment by pkittenis** [comment]
Hi, thanks for raising!

Have modified `version.py` to be python 3 compatible and fixed `pip install` via git tag - `0.5.0-rc3` is the latest release candidate.

```python
$ pip install https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz
  Downloading https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc3.tar.gz
     / 16kB 2.5MB/s
    /home/panos/graphite-influxdb/env/local/lib/python2.7/site-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.5.0rc3' instead of '0.5.0-rc3'.
      self.metadata.version,
Collecting graphite-api (from graphite-influxdb==0.5.0rc3)
```
