### ISSUE TITLE
graphite-influxdb multiple backends?

### ISSUE THREAD

**Issue by r3cgm** [pkittenis/graphite-influxdb#20]
Is there any way to run multiple instances each against a different DB backend?

Basically I want:

/etc/graphite-api-db1.yaml
  db: db1

/etc/graphite-api-db2.yaml
  db: db2

And I want to tell uwsgi to start and provide the first DB on port 8000 and the second on port 8001.

Thanks.

**Comment by pkittenis** [comment]
That's a [graphite-api](https://github.com/brutasse/graphite-api) question, cannot say. Issue tracker is for issues with this repository's code - keep that in mind :)
