### ISSUE TITLE
Question about HTTP caching

### ISSUE THREAD

**Issue by wavilen** [pkittenis/graphite-influxdb#4]
Hello. Please, add little bit more details to the README about HTTP caching.
I tried use your fork but catched giant performance degradation in Grafana UI in relative to native Grafite.

> Removed Elasticsearch get series names caching integration. An HTTP cache in front of the graphite-api webapp provides better performance at significantly less overhead.

Sorry for my ugly English.
Thanks!

**Comment by mbell697** [comment]
I'm using varnish for this, a config like follows seems to work well so far, still early on in testing the full setup under production load though.

```
vcl 4.0;

backend default {
    .host = "127.0.0.1";
    .port = "8888";
}

sub vcl_recv {
    # grafana passes it's cookie through the proxy which disables caching. Remove it.
    unset req.http.cookie;
}

sub vcl_backend_response {
    if (bereq.url ~ "^/metrics/") {
        set beresp.ttl = 15m;
        set beresp.grace = 15d;
    }
}
```

**Comment by pkittenis** [comment]
Also using Varnish for this, our config is similar to the above but without the 15m TTL on `/metrics`. 

We use the default 60 sec TTL to not have to wait 15min for new metric series to show up. Might end up raising TTL on `/metrics` if `/metrics/find` ends up taking a long time to return on large series lists.

Have updated the readme with this sample configuration.

```
backend default {
  .host = "127.0.0.1";
  .port = "<port>";
}

sub vcl_recv {
    unset req.http.cookie;
}
```
