### ISSUE TITLE
Allow configuration of the Influx aggregate function by metric name

### ISSUE THREAD

**Issue by mbell697** [pkittenis/graphite-influxdb#5]
The current implementation uses only `select mean(value)` in the Influx query. For some metrics this is the wrong aggregate function to be using, e.g. counters should queried with `select sum(value)` to give accurate numbers.

I think this should be configurable with a map of regex -> aggregate function to allow user configuration.

**Comment by pkittenis** [comment]
Resolved by `0.5.0-rc4`

```pip install https://github.com/pkittenis/graphite-influxdb/archive/0.5.0-rc4.tar.gz```

Example configuration and defaults defined on the main site's readme.
