### ISSUE TITLE
Graphite-Web

### ISSUE THREAD

**Issue by szop85** [pkittenis/graphite-influxdb#8]
Hey,

any idea where to find a for of graphite-web with InfluxDB compatibility? I'd like to test a combination of InfluxDB - collectd/diamond with Graphite-Web/Composer. BTW. kudos for this great API fork and work :) 

Cheers,
Szop

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

Getting started with graphite-api and Grafana as a composer is faster and simpler than setting up graphite-web and that is what I would recommend. There are instructions for Graphite-API on the main page, grafana works out of the box with either influxdb native or via graphite-api. There is no need for graphite-web.

If you must use graphite-web, see [parent project which claims to support Graphite-web](https://github.com/vimeo/graphite-influxdb).
