### ISSUE TITLE
Problems with metric resolution

### ISSUE THREAD

**Issue by hrzbrg** [pkittenis/graphite-influxdb#9]
Hi,

I have build a solid setup with graphite-influxdb & graphite-api recently. We collect metrics from ~250 docker containers and fill them into an InfluxDB. The data is then presented on dashboards in Grafana.

However I may have lost the overview a bit. We have measurements every 10s in the DB. But when I build a new graph in Grafana and have it pull the measurements, it only shows them as 1min averages.
Can I narrow this down to show every measurement or at least 30s averages?

A query in the influxd.log looks like this:
```[query] 2015/11/06 21:27:07 SELECT mean(value) AS "value" FROM "graphite"."90days"."docker.SOMECONTAINER.default.gauge.net.tx_bytes", "graphite"."90days"."docker.SOMECONTAINER.default.gauge.net.rx_bytes"
WHERE (time > 1446841627s AND time <= 1446845227s) GROUP BY time(1m)```

I thought this would be solved by setting a scheme in the graphite-api.yaml but your readme says that schemes are not needed. Also I don't know if this is really an issue with graphite-influxdb or with graphite-api. 
Maybe you can point me in the right direction to solve this. 

Regards
hrzbrg

**Comment by pkittenis** [comment]
Hello,

Per [documentation](https://github.com/pkittenis/graphite-influxdb#calculated-intervals), intervals are calculated dynamically based on the time range of the query. It's not a bug in either graphite-api nor graphite-influxdb.

The calculated intervals are not currently configurable though the [deltas variable](https://github.com/pkittenis/graphite-influxdb/blob/master/graphite_influxdb/utils.py#L14) can be edited to change them. Eg to allow for 30 sec intervals if time range is under a day, uncomment [this line](https://github.com/pkittenis/graphite-influxdb/blob/master/graphite_influxdb/utils.py#L18).

Have raised #10 to make the intervals configurable.
